version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: system_gear_ec
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c log_statement=all

volumes:
  postgres_data: