[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x']

[phases.install]
cmds = ['npm ci --legacy-peer-deps']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npx serve -s build -l $PORT'

[variables]
NPM_CONFIG_PRODUCTION = 'false'
REACT_APP_API_URL = 'https://backend-api-production-808a.up.railway.app/api'